title="Hamster Config"

[author]
name="Adnaan Badr"
organization="hamster"
email="badr.adnaan@gmail.com"

[servers]

	[servers.local]
	port = 8686
	host = "http://localhost:8686"

[databases]

	[databases.mongo]
	username =""
	password=""
	dbname=""
	host="mongodb://adnaan:pass@localhost:27017/hamster"

[clients]
	
	[clients.browser]
	secret="mysharedsecret"

[logins]
	
	[logins.google]
	id= "a69c7cca3b3121a40934"
	secret="1ac41f49814k9asdfs9fd798we87s8f79904abaa91ac.apps.googleusercontent.com"
